[package]
name = "rckit"
license = "MIT"
version = "0.1.0"
authors = ["lintanghui <lintanghui@bilibili.com>"]

[dependencies]
clap="2.23.0"
redis="0.9.0"
[lib]
name="rckit"
path="src/lib.rs"
[[bin]]
name="rckit"
path="bin/main.rs"